# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PR

on:
  pull_request:
    branches: 
      - main
# Ignoring the docs prevents PRs touching only docs from succeeding.
# Also, the docs do have a build step which must succeed for overall builds to succeed.
#    paths-ignore:
#      - "docs/**"

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn

      - name: Code Format Check
        run: yarn format:check

      - name: Check Change Files
        run: yarn checkchange

      - name: Code Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

